test:
	./gradlew test --info

build:
	./gradlew installDist --warning-mode all

check-style:
	./gradlew checkstyleMain checkstyleTest

run:
	./gradlew clean build run

.PHONY: build test check-style run